[package]
name = "waml-markdown-editor"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "WAML-owned variable-metric Markdown editing foundation."

[dependencies]
waml-syntax = { path = "../waml-syntax" }
makepad-widgets = { git = "https://github.com/redoz/makepad.git", rev = "92df3316b8e8d3cb879e63a53bb0fa047681d8fd" }
unicode-segmentation = { workspace = true }
unicode-bidi = { workspace = true }
