[package]
name = "waml-ui-test"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
makepad-test = { git = "https://github.com/redoz/makepad.git", rev = "6534634a60aa8101fa93bb1ddf0edde6949e520a" }
makepad-widgets = { git = "https://github.com/redoz/makepad.git", rev = "6534634a60aa8101fa93bb1ddf0edde6949e520a" }
serde.workspace = true
serde_json.workspace = true
waml-ui-test-macros = { path = "../waml-ui-test-macros" }

[dev-dependencies]
tempfile.workspace = true
