[package]
name = "waml-ui-test"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
makepad-test = { git = "https://github.com/redoz/makepad.git", rev = "9e428ab8b77fc3d5beaa78296646aff88b82bd9b" }
makepad-widgets = { git = "https://github.com/redoz/makepad.git", rev = "9e428ab8b77fc3d5beaa78296646aff88b82bd9b" }
serde.workspace = true
serde_json.workspace = true
waml-ui-test-macros = { path = "../waml-ui-test-macros" }

[dev-dependencies]
tempfile.workspace = true
