[package]
name = "waml-ui-test"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
makepad-test = { workspace = true }
makepad-widgets = { workspace = true }
serde.workspace = true
serde_json.workspace = true
waml-ui-test-macros = { path = "../waml-ui-test-macros" }

[dev-dependencies]
tempfile.workspace = true
