// GENERATED by gen-bundle.gen.test.ts — do not edit by hand.
// The Orders Domain template as a committed `.okf` bundle (the WASM core's
// `[path, markdown][]` shape). It is the in-memory source of truth for this
// template; `build_model` derives the Model from it.
export const ordersDomainBundle: [string, string][] = [
  [
    "orders-domain-uml/order.md",
    "---\ntype: \"uml.Class\"\nstereotype: [\"aggregateRoot\", \"entity\"]\ntitle: \"Order\"\ndescription: \"A customer's placed order.\"\n---\n\n# Order\n\n## Attributes\n- id: OrderId\n- placedAt: Timestamp\n- status: [OrderStatus](./order-status.md)\n- shippingAddress: [Address](./address.md) {0..1}\n- total: [Money](./money.md)\n\n## Relationships\n- associates [Customer](./customer.md): 1 order to 1 customer\n- composes [OrderLine](./order-line.md): 1 to 1..* lines\n- depends [PricingService](./pricing-service.md)\n\n"
  ],
  [
    "orders-domain-uml/order-line.md",
    "---\ntype: \"uml.Class\"\nstereotype: [\"entity\"]\ntitle: \"OrderLine\"\n---\n\n# OrderLine\n\n## Attributes\n- quantity: Int\n- unitPrice: [Money](./money.md)\n\n"
  ],
  [
    "orders-domain-uml/customer.md",
    "---\ntype: \"uml.Class\"\nstereotype: [\"aggregateRoot\", \"entity\"]\ntitle: \"Customer\"\n---\n\n# Customer\n\n## Attributes\n- id: CustomerId\n- name: String\n- email: Email\n\n"
  ],
  [
    "orders-domain-uml/order-status.md",
    "---\ntype: \"uml.Enum\"\ntitle: \"OrderStatus\"\n---\n\n# OrderStatus\n\n## Values\n- DRAFT\n- PLACED\n- SHIPPED\n- CANCELLED\n\n"
  ],
  [
    "orders-domain-uml/money.md",
    "---\ntype: \"uml.DataType\"\nstereotype: [\"valueObject\"]\ntitle: \"Money\"\n---\n\n# Money\n\n## Attributes\n- amount: Decimal\n- currency: CurrencyCode\n\n"
  ],
  [
    "orders-domain-uml/address.md",
    "---\ntype: \"uml.Class\"\nstereotype: [\"valueObject\"]\ntitle: \"Address\"\n---\n\n# Address\n\n## Attributes\n- street: String\n- city: String\n- country: CountryCode\n\n"
  ],
  [
    "orders-domain-uml/pricing-service.md",
    "---\ntype: \"uml.Interface\"\nstereotype: [\"service\"]\ntitle: \"PricingService\"\n---\n\n# PricingService\n\n"
  ],
  [
    "orders-domain-uml/orders-domain.md",
    "---\ntype: \"Diagram\"\ntitle: \"Orders Domain Model\"\nprofile: \"uml-domain\"\n---\n\n# Orders Domain Model\n\n## Members\n- [Order](./order.md)\n- [OrderLine](./order-line.md)\n- [Customer](./customer.md)\n- [OrderStatus](./order-status.md)\n- [Money](./money.md)\n- [Address](./address.md)\n- [PricingService](./pricing-service.md)\n"
  ],
  [
    "orders-domain-uml/index.md",
    "---\ntype: \"index\"\ntitle: \"Orders Domain (UML)\"\ndescription: \"Index of exported documents.\"\n---\n\n# Orders Domain (UML)\n\n| Document | Type |\n|----------|------|\n| [Order](./order.md) | uml.Class |\n| [OrderLine](./order-line.md) | uml.Class |\n| [Customer](./customer.md) | uml.Class |\n| [OrderStatus](./order-status.md) | uml.Enum |\n| [Money](./money.md) | uml.DataType |\n| [Address](./address.md) | uml.Class |\n| [PricingService](./pricing-service.md) | uml.Interface |\n"
  ]
];
