// AUTO-GENERATED by `waml bundle` — do not edit by hand.
export const ordersUseCasesBundle: [string, string][] = [
  ["orders-use-cases/authenticate.md", "---\ntype: \"uml.UseCase\"\ntitle: \"Authenticate\"\n---\n\n# Authenticate\n"],
  ["orders-use-cases/cancel-order.md", "---\ntype: \"uml.UseCase\"\ntitle: \"Cancel Order\"\n---\n\n# Cancel Order\n\n## Relationships\n- associates [Customer](./customer.md)\n- extends [Place Order](./place-order.md)\n"],
  ["orders-use-cases/customer.md", "---\ntype: \"uml.Actor\"\ntitle: \"Customer\"\n---\n\n# Customer\n"],
  ["orders-use-cases/orders-use-cases.md", "---\ntype: \"Diagram\"\ntitle: \"Orders Use Cases\"\nprofile: \"uml-domain\"\n---\n\n# Orders Use Cases\n\n## Members\n\n### Actors\n- [Customer](./customer.md)\n\n### Use Cases\n- [Place Order](./place-order.md)\n- [Authenticate](./authenticate.md)\n- [Track Order](./track-order.md)\n- [Cancel Order](./cancel-order.md)\n"],
  ["orders-use-cases/place-order.md", "---\ntype: \"uml.UseCase\"\ntitle: \"Place Order\"\n---\n\n# Place Order\n\n## Relationships\n- associates [Customer](./customer.md)\n- includes [Authenticate](./authenticate.md)\n"],
  ["orders-use-cases/track-order.md", "---\ntype: \"uml.UseCase\"\ntitle: \"Track Order\"\n---\n\n# Track Order\n\n## Relationships\n- associates [Customer](./customer.md)\n"],
];
