pub use makepad_widgets;
use makepad_widgets::*;

mod action_link;
mod app;
mod attr_row;
mod camera;
mod canvas;
mod card;
mod class_diagram_view;
mod classifier_preview_view;
mod cli;
mod colors_overlay;
mod config;
mod conflict_badge;
mod diagram_switcher;
mod doc_tabs;
mod doc_view;
mod dock;
mod fonts;
mod fonts_overlay;
mod fps_meter;
mod frame;
mod icon_button;
mod icons;
mod icons_overlay;
mod inspector;
mod inspector_panel;
mod load;
mod logo;
mod nav;
mod node_design_editor;
mod node_style;
mod overlay_shell;
mod panel_glass;
mod popup;
mod recent_row;
mod ref_card;
mod scene;
mod section_heading;
mod select_box;
mod selection_toolbar;
mod shortcuts_overlay;
mod sizing;
mod source_view;
mod start_screen;
mod statusbar;
mod theme_atlas;
mod tool_dock;
mod tree;
mod tree_panel;
mod veil;
mod view_bar;

use app::App;

app_main!(App);
