[package]
name = "waml"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Core library for parsing, serializing, and validating WAML documents."

[dependencies]
regex.workspace = true
pulldown-cmark.workspace = true
miniz_oxide.workspace = true
ttf-parser.workspace = true
serde = { workspace = true, optional = true }
waml-syntax = { path = "../waml-syntax" }

[features]
default = []
serde = ["dep:serde"]
test-support = []

[dev-dependencies]
serde_json = { workspace = true }
proptest.workspace = true
