use serde::Serialize;
use waml::action::SyntaxChangeBatch;
use waml::analysis::{prepare_candidate, PreparedCandidate, PreviousAnalyses};
use waml::diagnostic::{Diagnostic, Severity};
use waml::edit::{EditBatch, EditContext};
use waml::index_md::reindex_source;
use waml::source::{BundlePath, SourceBundle};
use waml::uml::{ActionContext, Formatter};

#[derive(Serialize)]
struct DiagDto<'a> {
    severity: &'a str,
    code: &'a str,
    message: &'a str,
    file: &'a str,
    line: usize,
    #[serde(skip_serializing_if = "Option::is_none")]
    span: Option<(usize, usize)>,
}

fn severity_str(s: Severity) -> &'static str {
    match s {
        Severity::Error => "error",
        Severity::Warning => "warning",
    }
}

fn sorted(diags: &[Diagnostic]) -> Vec<&Diagnostic> {
    let mut v: Vec<&Diagnostic> = diags.iter().collect();
    v.sort_by(|a, b| a.file.cmp(&b.file).then(a.line.cmp(&b.line)));
    v
}

pub fn render_human(diags: &[Diagnostic]) -> String {
    if diags.is_empty() {
        return "No problems found.".to_string();
    }
    let mut lines = Vec::new();
    for d in sorted(diags) {
        // `span` is 0-based byte columns within the line; print 1-based
        // columns to match the 1-based `line`.
        let location = match d.span {
            Some((start, end)) => format!("{}:{}:{}-{}", d.file, d.line, start + 1, end + 1),
            None => format!("{}:{}", d.file, d.line),
        };
        lines.push(format!(
            "{location}: {}[{}]: {}",
            severity_str(d.severity),
            d.code.as_str(),
            d.message
        ));
    }
    let errors = diags
        .iter()
        .filter(|d| d.severity == Severity::Error)
        .count();
    let warnings = diags.len() - errors;
    lines.push(format!("\n{errors} error(s), {warnings} warning(s)."));
    lines.join("\n")
}

pub fn render_json(diags: &[Diagnostic]) -> String {
    let dtos: Vec<DiagDto> = sorted(diags)
        .into_iter()
        .map(|d| DiagDto {
            severity: severity_str(d.severity),
            code: d.code.as_str(),
            message: &d.message,
            file: &d.file,
            line: d.line,
            span: d.span,
        })
        .collect();
    serde_json::to_string_pretty(&dtos).unwrap_or_else(|_| "[]".to_string())
}

fn diff_lines(a: &str, b: &str) -> String {
    let al: Vec<&str> = a.lines().collect();
    let bl: Vec<&str> = b.lines().collect();
    let mut s = 0;
    while s < al.len() && s < bl.len() && al[s] == bl[s] {
        s += 1;
    }
    let (mut ea, mut eb) = (al.len(), bl.len());
    while ea > s && eb > s && al[ea - 1] == bl[eb - 1] {
        ea -= 1;
        eb -= 1;
    }
    let mut out = String::new();
    for l in &al[s..ea] {
        out.push_str(&format!("-{l}\n"));
    }
    for l in &bl[s..eb] {
        out.push_str(&format!("+{l}\n"));
    }
    out
}

/// Render a human-readable summary of changes between an old and new bundle:
/// `~ path` (changed, with unified-ish added/removed lines), `+ path (new)`,
/// `- path (deleted)`.
pub fn render_diff(old: &[(String, String)], new: &[(String, String)]) -> String {
    use std::collections::BTreeMap;
    let om: BTreeMap<&str, &str> = old.iter().map(|(p, c)| (p.as_str(), c.as_str())).collect();
    let nm: BTreeMap<&str, &str> = new.iter().map(|(p, c)| (p.as_str(), c.as_str())).collect();
    let mut out = String::new();
    for (p, c) in &nm {
        match om.get(p) {
            Some(old_c) if old_c == c => {}
            Some(old_c) => {
                out.push_str(&format!("~ {p}\n"));
                out.push_str(&diff_lines(old_c, c));
            }
            None => {
                out.push_str(&format!("+ {p} (new)\n"));
                out.push_str(&diff_lines("", c));
            }
        }
    }
    for p in om.keys() {
        if !nm.contains_key(p) {
            out.push_str(&format!("- {p} (deleted)\n"));
        }
    }
    if out.is_empty() {
        out.push_str("no changes\n");
    }
    out
}

pub fn render_bundle_json(bundle: &[(String, String)]) -> String {
    serde_json::to_string_pretty(bundle).unwrap_or_else(|_| "[]".to_string())
}

/// True iff `name` can sit verbatim in `export const {name}` — an ASCII
/// identifier. Anything else would splice arbitrary text into the generated
/// TypeScript, so [`render_bundle_ts`] callers must reject it first.
pub fn is_ts_export_name(name: &str) -> bool {
    let mut chars = name.chars();
    chars
        .next()
        .is_some_and(|c| c.is_ascii_alphabetic() || c == '_' || c == '$')
        && chars.all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '$')
}

/// Emit a checked-in TS module: `serde_json::to_string` per field reuses JSON string
/// escaping, which is valid JS/TS string literal syntax.
pub fn render_bundle_ts(bundle: &[(String, String)], export_name: &str) -> String {
    let mut out = String::from("// AUTO-GENERATED by `waml bundle` — do not edit by hand.\n");
    out.push_str(&format!(
        "export const {export_name}: [string, string][] = [\n"
    ));
    for (path, content) in bundle {
        let path_json = serde_json::to_string(path).unwrap_or_else(|_| "\"\"".to_string());
        let content_json = serde_json::to_string(content).unwrap_or_else(|_| "\"\"".to_string());
        out.push_str(&format!("  [{path_json}, {content_json}],\n"));
    }
    out.push_str("];\n");
    out
}

pub fn check_exit_code(diags: &[Diagnostic]) -> i32 {
    if diags.iter().any(|d| d.severity == Severity::Error) {
        1
    } else {
        0
    }
}

pub struct FmtResult {
    pub path: String,
    pub formatted: String,
    pub changed: bool,
    pub skipped: bool,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum IndexChange {
    Upsert { path: String, rendered: String },
    Remove { path: String },
}

pub fn prepare(files: &[(String, String)]) -> Result<PreparedCandidate, String> {
    let source = SourceBundle::try_from_pairs(files.iter().cloned()).map_err(|e| e.to_string())?;
    prepare_candidate(source, None, 0).map_err(|e| e.to_string())
}

/// Build the export-time search-index asset for `files` (spec: `waml export
/// site`'s static bundle also ships its index). The index is built from
/// exactly the pairs `files` holds -- the same pairs that go into
/// `bundle.waml` -- so search on the exported site can never see more than
/// the export shipped, and `bundle_hash(files)` is what a boot-time decode
/// must reproduce to accept the asset.
pub fn build_search_index_asset(files: &[(String, String)]) -> Result<Vec<u8>, String> {
    let prepared = prepare(files)?;
    let fields =
        waml::search::extract::extract_bundle(prepared.source(), prepared.okf(), prepared.uml());
    let index = waml::search::MemSearchIndex::build(fields);
    let hash = waml::search::asset::bundle_hash(files);
    Ok(waml::search::asset::encode(&index, hash).into_bytes())
}

pub fn plan_indexes(files: &[(String, String)]) -> Result<Vec<IndexChange>, String> {
    let mut original_index_paths = std::collections::BTreeMap::new();
    let mut planning_files = Vec::with_capacity(files.len());
    for (path, text) in files {
        let (directory, basename) = path.rsplit_once('/').unwrap_or(("", path));
        let planning_path = if basename.eq_ignore_ascii_case("index.md") {
            if directory.is_empty() {
                "index.md".to_string()
            } else {
                format!("{directory}/index.md")
            }
        } else {
            path.clone()
        };
        if basename.eq_ignore_ascii_case("index.md") {
            if let Some(existing) = original_index_paths.insert(planning_path.clone(), path.clone())
            {
                if existing != *path {
                    return Err(format!("index basename collision: {existing} and {path}"));
                }
            }
        }
        planning_files.push((planning_path, text.clone()));
    }

    let prepared = prepare(&planning_files)?;
    let before: std::collections::BTreeMap<String, String> =
        prepared.source().to_pairs().into_iter().collect();
    let mut after: std::collections::BTreeMap<String, String> = reindex_source(prepared.source())
        .to_pairs()
        .into_iter()
        .collect();
    let mut desired_index_directories = std::collections::BTreeSet::from([String::new()]);
    for path in before.keys() {
        let basename = path.rsplit('/').next().unwrap_or(path);
        if basename.eq_ignore_ascii_case("index.md") {
            continue;
        }
        let mut parent = path.rsplit_once('/').map(|(parent, _)| parent);
        while let Some(directory) = parent {
            desired_index_directories.insert(directory.to_string());
            parent = directory.rsplit_once('/').map(|(parent, _)| parent);
        }
    }
    after.retain(|path, _| {
        let (directory, basename) = path.rsplit_once('/').unwrap_or(("", path));
        !basename.eq_ignore_ascii_case("index.md") || desired_index_directories.contains(directory)
    });
    let paths: std::collections::BTreeSet<_> = before.keys().chain(after.keys()).collect();
    let mut changes = Vec::new();

    for path in paths {
        if !path
            .rsplit('/')
            .next()
            .is_some_and(|name| name.eq_ignore_ascii_case("index.md"))
        {
            continue;
        }
        if before.get(path) == after.get(path) {
            continue;
        }
        match after.get(path) {
            Some(rendered) => changes.push(IndexChange::Upsert {
                path: original_index_paths
                    .get(path)
                    .cloned()
                    .unwrap_or_else(|| path.clone()),
                rendered: rendered.clone(),
            }),
            None => changes.push(IndexChange::Remove {
                path: original_index_paths
                    .get(path)
                    .cloned()
                    .unwrap_or_else(|| path.clone()),
            }),
        }
    }

    Ok(changes)
}

pub fn diagnostics(
    candidate: &PreparedCandidate,
    display_paths: &std::collections::BTreeMap<String, String>,
) -> Vec<Diagnostic> {
    candidate
        .uml()
        .diagnostics
        .iter()
        .cloned()
        .map(|mut diagnostic| {
            if let Some(display) = display_paths.get(&diagnostic.file) {
                diagnostic.file.clone_from(display);
            }
            diagnostic
        })
        .collect()
}

pub fn plan_fmt(files: &[(String, String)]) -> Result<Vec<FmtResult>, String> {
    let prepared = prepare(files)?;
    let action_context = ActionContext::from_prepared(&prepared).map_err(|e| e.to_string())?;
    let mut candidate_pairs: std::collections::BTreeMap<String, String> =
        prepared.source().to_pairs().into_iter().collect();

    for source_document in prepared.source().documents() {
        let document = prepared
            .okf()
            .catalog
            .id_for_path(source_document.path())
            .ok_or_else(|| format!("catalog has no document: {}", source_document.path()))?;
        let version = prepared
            .okf()
            .catalog
            .document(document)
            .ok_or_else(|| format!("catalog has no document: {}", source_document.path()))?;
        if prepared.uml().syntax.document(document).is_none() {
            continue;
        }
        let action = Formatter
            .format(
                ActionContext::new(
                    action_context.okf(),
                    action_context.uml(),
                    action_context.session_revision(),
                )
                .map_err(|e| e.to_string())?,
                document,
            )
            .map_err(|e| e.to_string())?;
        let formatted = SyntaxChangeBatch::new(action)
            .map_err(|e| e.to_string())?
            .lower(EditContext {
                source: prepared.source(),
                okf_analysis: prepared.okf(),
                session_revision: prepared.revision(),
                uml: prepared.uml(),
            })
            .map_err(|e| e.to_string())?;
        let formatted_document = formatted
            .document(version.path())
            .ok_or_else(|| format!("formatted document disappeared: {}", version.path()))?;
        if formatted_document.text() != version.text().shared().as_str() {
            candidate_pairs.insert(
                version.path().to_string(),
                formatted_document.text().to_owned(),
            );
        }
    }

    let validated = prepare_candidate(
        SourceBundle::try_from_pairs(candidate_pairs).map_err(|e| e.to_string())?,
        Some(PreviousAnalyses {
            okf: prepared.okf(),
            uml: prepared.uml(),
        }),
        1,
    )
    .map_err(|e| e.to_string())?;
    let diagnostics = diagnostics(&validated, &std::collections::BTreeMap::new());
    Ok(files
        .iter()
        .map(|(path, original)| {
            let bundle_path = BundlePath::parse(path.clone()).expect("prepared path is valid");
            let document = validated
                .okf()
                .catalog
                .id_for_path(&bundle_path)
                .expect("validated catalog document exists");
            let formatted = validated
                .source()
                .document(&bundle_path)
                .expect("validated document exists")
                .text()
                .to_owned();
            let is_index = path
                .rsplit('/')
                .next()
                .is_some_and(|segment| segment.eq_ignore_ascii_case("index.md"));
            let claimed = prepared.uml().syntax.document(document);
            let skipped = !is_index
                && (diagnostics.iter().any(|diagnostic| {
                    diagnostic.file == *path && diagnostic.severity == Severity::Error
                }) || claimed
                    .is_some_and(|snapshot| !snapshot.syntax().diagnostics().is_empty())
                    || (claimed.is_some()
                        && prepared
                            .uml()
                            .markdown
                            .document(document)
                            .is_some_and(|snapshot| {
                                let structure = snapshot.structure();
                                let Some(h1) =
                                    structure.headings.iter().find(|heading| heading.level == 1)
                                else {
                                    return false;
                                };
                                let after_h1 = original[h1.range.end().to_usize()..]
                                    .find('\n')
                                    .map(|offset| h1.range.end().to_usize() + offset + 1)
                                    .unwrap_or_else(|| h1.range.end().to_usize());
                                let first_h2 = structure
                                    .headings
                                    .iter()
                                    .find(|heading| heading.level == 2)
                                    .map(|heading| heading.range.start().to_usize())
                                    .unwrap_or(original.len());
                                after_h1 < first_h2
                                    && !original[after_h1..first_h2].trim().is_empty()
                            })));
            FmtResult {
                path: path.clone(),
                changed: !skipped && formatted != *original,
                formatted: if skipped { original.clone() } else { formatted },
                skipped,
            }
        })
        .collect())
}

#[cfg(test)]
mod tests {
    use super::*;
    use waml::diagnostic::DiagCode;

    #[test]
    fn build_search_index_asset_carries_the_bundle_hash_and_finds_known_terms() {
        let files = vec![(
            "order.md".to_string(),
            "---\ntype: uml.Class\n---\n# Order\n\nAbout payments.\n".to_string(),
        )];

        let bytes = build_search_index_asset(&files).unwrap();
        let text = String::from_utf8(bytes).unwrap();
        let hash = waml::search::asset::bundle_hash(&files);
        assert!(
            text.starts_with(&format!(
                "waml-search-index v{} {hash}",
                waml::search::asset::FORMAT_VERSION
            )),
            "{text}"
        );

        let index = waml::search::asset::decode(&text, hash).unwrap();
        use waml::search::SearchIndex;
        assert!(!index
            .query("payments", &waml::search::QueryScope::default())
            .is_empty());

        // A different bundle's hash must not decode this asset (spec: the
        // export boundary is hash-checked, not merely versioned).
        let other = vec![("order.md".to_string(), "# Order\n".to_string())];
        let other_hash = waml::search::asset::bundle_hash(&other);
        assert!(waml::search::asset::decode(&text, other_hash).is_err());
    }

    #[test]
    fn plan_indexes_keeps_deep_ancestors_and_removes_an_orphan_index() {
        let files = vec![
            (
                "alpha/beta/order.md".to_string(),
                "---\ntype: uml.Class\ntitle: Order\n---\n# Order\n".to_string(),
            ),
            ("orphan/Index.md".to_string(), "# Orphan\n".to_string()),
        ];

        let changes = plan_indexes(&files).unwrap();
        let changes = changes
            .iter()
            .map(|change| match change {
                IndexChange::Upsert { path, .. } => ("upsert", path.as_str()),
                IndexChange::Remove { path } => ("remove", path.as_str()),
            })
            .collect::<Vec<_>>();

        assert_eq!(
            changes,
            [
                ("upsert", "alpha/beta/index.md"),
                ("upsert", "alpha/index.md"),
                ("upsert", "index.md"),
                ("remove", "orphan/Index.md"),
            ]
        );
    }

    #[test]
    fn plan_indexes_rejects_case_colliding_index_paths() {
        let files = vec![
            ("nested/index.md".to_string(), "# Lower\n".to_string()),
            ("nested/Index.md".to_string(), "# Mixed\n".to_string()),
        ];

        let error = plan_indexes(&files).unwrap_err();

        assert!(error.contains("nested/index.md"), "{error}");
        assert!(error.contains("nested/Index.md"), "{error}");
    }

    #[test]
    fn plan_fmt_leaves_index_docs_untouched() {
        // An index doc's navigation is not round-trippable through the node
        // serializer (it would be dropped), so fmt must pass it through verbatim
        // rather than skip it as errored or rewrite it and lose the nav.
        let files = vec![
            (
                "alerts/index.md".to_string(),
                "# Alerts\n\nAlert docs.\n\n* [Alert](./alert.md) - a signal\n".to_string(),
            ),
            (
                "alerts/alert.md".to_string(),
                "---\ntype: uml.Class\ntitle: Alert\n---\n# Alert\n".to_string(),
            ),
        ];
        let out = plan_fmt(&files).unwrap();
        let ix = out.iter().find(|r| r.path == "alerts/index.md").unwrap();
        assert!(!ix.skipped, "index doc must not be skipped as errored");
        assert!(!ix.changed, "index nav must be preserved verbatim");
        assert_eq!(
            ix.formatted, files[0].1,
            "index content must round-trip unchanged"
        );
    }

    fn sample() -> Vec<Diagnostic> {
        vec![
            Diagnostic::new(
                DiagCode::UnresolvedTarget,
                "no doc './ghost.md'",
                "a/order.md",
                8,
            ),
            Diagnostic::warn(
                DiagCode::UnknownType,
                "unknown type 'bpmn.Task'",
                "a/x.md",
                2,
            ),
        ]
    }

    #[test]
    fn human_output_has_file_line_and_code() {
        let out = render_human(&sample());
        assert!(out.contains("a/order.md:8: error[unresolved-target]: no doc './ghost.md'"));
        assert!(out.contains("a/x.md:2: warning[unknown-type]:"));
    }

    #[test]
    fn human_output_includes_the_column_span_when_present() {
        let diags = vec![
            Diagnostic::new(DiagCode::MalformedAttribute, "bad", "a.md", 8).with_span((2, 20)),
        ];
        let out = render_human(&diags);
        assert!(
            out.contains("a.md:8:3-21: error[malformed-attribute]: bad"),
            "{out}"
        );
    }

    #[test]
    fn json_output_is_an_array_of_diagnostics() {
        let out = render_json(&sample());
        let v: serde_json::Value = serde_json::from_str(&out).unwrap();
        assert_eq!(v.as_array().unwrap().len(), 2);
        assert_eq!(v[0]["code"], "unresolved-target");
        assert_eq!(v[0]["line"], 8);
    }

    #[test]
    fn json_output_includes_span_when_present() {
        let diags = vec![
            Diagnostic::new(DiagCode::MalformedAttribute, "bad", "a.md", 8).with_span((2, 20)),
        ];
        let out = render_json(&diags);
        let v: serde_json::Value = serde_json::from_str(&out).unwrap();
        assert_eq!(v[0]["span"][0], 2);
        assert_eq!(v[0]["span"][1], 20);
    }

    #[test]
    fn plan_fmt_still_skips_error_files_byte_for_byte() {
        let original = "---\ntype: uml.Class\ntitle: A\n---\n# A\n\nDo not lose this sentence.\n\n## Attributes\n- id: AId\n";
        let files = vec![("x/a.md".to_string(), original.to_string())];
        let plan = plan_fmt(&files).unwrap();
        assert!(plan[0].skipped);
        assert_eq!(plan[0].formatted, original);
    }

    #[test]
    fn exit_code_is_one_with_errors_zero_with_only_warnings() {
        assert_eq!(check_exit_code(&sample()), 1);
        let only_warn = vec![Diagnostic::warn(DiagCode::UnknownType, "w", "a.md", 1)];
        assert_eq!(check_exit_code(&only_warn), 0);
        assert_eq!(check_exit_code(&[]), 0);
    }

    #[test]
    fn formats_a_clean_file_and_detects_change() {
        // An authored default `{1}` is preserved by canonical form.
        let files = vec![(
            "x/a.md".to_string(),
            "---\ntype: uml.Class\ntitle: A\n---\n# A\n\n## Attributes\n- id: AId {1}\n"
                .to_string(),
        )];
        let plan = plan_fmt(&files).unwrap();
        assert_eq!(plan.len(), 1);
        assert!(!plan[0].skipped);
        assert!(plan[0].changed);
        assert!(plan[0].formatted.contains("- id: AId {1}\n"));
    }

    #[test]
    fn skips_a_file_with_errors() {
        let files = vec![(
            "x/a.md".to_string(),
            "---\ntype: uml.Class\ntitle: A\n---\n# A\n\n## Attributes\n- broken line\n"
                .to_string(),
        )];
        let plan = plan_fmt(&files).unwrap();
        assert!(plan[0].skipped);
        assert!(!plan[0].changed);
    }

    #[test]
    fn skips_a_file_with_pre_section_prose_instead_of_dropping_it() {
        // Regression: prose between the H1 title and the first `## ` section
        // used to be silently dropped by parse -> serialize with no
        // diagnostic, so `fmt` would rewrite the file and delete it. Now
        // `validate` flags it as an Error, so `plan_fmt` must skip the file
        // and leave its content byte-for-byte untouched.
        let original = "---\ntype: uml.Class\ntitle: A\n---\n# A\n\nDo not lose this sentence.\n\n## Attributes\n- id: AId\n";
        let files = vec![("x/a.md".to_string(), original.to_string())];
        let plan = plan_fmt(&files).unwrap();
        assert_eq!(plan.len(), 1);
        assert!(
            plan[0].skipped,
            "expected the file to be skipped, not silently rewritten"
        );
        assert!(!plan[0].changed);
        assert_eq!(
            plan[0].formatted, original,
            "skipped content must be byte-for-byte untouched"
        );
    }

    #[test]
    fn render_bundle_json_round_trips() {
        let bundle = vec![("a/one.md".to_string(), "# One\n".to_string())];
        let out = render_bundle_json(&bundle);
        let v: Vec<(String, String)> = serde_json::from_str(&out).unwrap();
        assert_eq!(v, bundle);
    }

    #[test]
    fn render_bundle_ts_emits_valid_export_with_escaped_content() {
        let bundle = vec![("a/one.md".to_string(), "line1\n\"quoted\"\n".to_string())];
        let out = render_bundle_ts(&bundle, "myBundle");
        assert!(out.starts_with("// AUTO-GENERATED"));
        assert!(out.contains("export const myBundle: [string, string][] = ["));
        assert!(out.contains("\"a/one.md\""));
        assert!(out.contains("\\n\\\"quoted\\\"\\n"));
    }

    #[test]
    fn ts_export_names_admit_identifiers_and_nothing_else() {
        for valid in ["myBundle", "_private", "$x", "b2", "SNAKE_CASE"] {
            assert!(is_ts_export_name(valid), "{valid}");
        }
        for invalid in [
            "",
            "2start",
            "has space",
            "a-b",
            "x;alert(1)//",
            "a\"] = evil; //",
            "café",
        ] {
            assert!(!is_ts_export_name(invalid), "{invalid}");
        }
    }

    #[test]
    fn render_diff_shows_added_changed_deleted() {
        let old = vec![
            ("a.md".to_string(), "x\ny\n".to_string()),
            ("gone.md".to_string(), "z\n".to_string()),
        ];
        let new = vec![
            ("a.md".to_string(), "x\nY\n".to_string()),
            ("new.md".to_string(), "q\n".to_string()),
        ];
        let d = render_diff(&old, &new);
        assert!(d.contains("a.md"));
        assert!(d.contains("-y"));
        assert!(d.contains("+Y"));
        assert!(d.contains("new.md")); // added
        assert!(d.contains("gone.md")); // deleted
    }
}
